- general:
    - ConstantsInInterfaceCheck:
        ignoreIfHasMethods: False
    - CopyPasteCheck:
        tokenCount: 100
    - DoubleBraceInitializationCheck
    - ForToForEachCheck
    - MissingOverrideAnnotationCheck
    - EqualsContractCheck
    - CompareObjectsNotStringsCheck
    - ConstantNamingAndQualifierCheck
    - DontReassignParametersCheck
    - FieldShouldBeLocalCheck
- api:
    - IsEmptyReimplementationCheck
    - OldCollectionCheck
    - StringIsEmptyReimplementationCheck
- complexity:
    - DiamondOperatorCheck
    - ExtendsObjectCheck
    - ForLoopVariableCheck
    - RedundantModifierCheck
    - RedundantReturnCheck
    - UnnecessaryLocalBeforeReturnCheck
    - UnusedImportCheck
    - WrapperInstantiationCheck
- debug:
    - AssertCheck
    - PrintStackTraceCheck
- exceptions:
    - EmptyCatchCheck
- comment:
    - JavadocReturnNullCheck
    - CommentLanguageCheck
    - JavadocStubCheck
    - CommentedOutCodeCheck
    - AuthorTagCheck:
        regex: u(\w){4}
    - JavadocParamCheck
- naming:
    - BooleanMethodNameCheck
    - LinguisticNamingCheck
    - VariablesHaveDescriptiveNamesCheck
- oop:
    - ConcreteCollectionCheck
    - MethodShouldBeAbstractCheck
- structure:
    - DefaultPackageCheck
- unnecessary:
    - EmptyNonCatchBlockCheck
    - UnusedCodeElementCheck
