name: Blank Issue
description: Create an issue that does not fit any of the other templates
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making an issue!

        Please ensure that **no personal information** is in any code.
  - type: textarea
    id: problem
    attributes:
      label: Description
      description: >
        Please provide a description of the issue, along with any information
        you feel relevant to replicate it.
    validations:
      required: true
