name: Bug Report (Crash)
description: Create a bug report about the autograder crashing
labels: ["bug", "crash"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a bug report!

        Please ensure that **no personal information** is in any code.
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: input
    id: lint-name
    attributes:
      label: Lint Name
      description: Please provide the lint name.
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: Please provide the code (without personal information) that triggers the bug
      value: |
        ```java
        <code>
        ```
  - type: textarea
    id: error
    attributes:
      label: Error output
      description: >
        Include a backtrace in the code block. You can find the backtrace in the eclipse workspace under `.metadata/.log`.
        Or Window > Show View > Other then select General > Error Log. This will open the Error Log view, where you
        can find the backtrace as well.
      value: |
        <details><summary>Backtrace</summary>
          <p>

          ```
          <backtrace>
          ```

          </p>
        </details>
