name: Bug Report (False Positive)
description: Create a bug report about wrongly emitted warnings from a lint
labels: ["bug", "false-positive"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a bug report!

        Please ensure that **no personal information** is in any code.
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: input
    id: lint-name
    attributes:
      label: Lint Name
      description: Please provide the lint name.
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: Please provide the code (without personal information) that triggers the bug
      value: |
        ```java
        <code>
        ```
