name: New lint suggestion
description: A new lint that should be added to the autograder
labels: ["new-lint", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for the lint idea!
  - type: textarea
    id: what
    attributes:
      label: What it does
      description: What does this lint do?
  - type: input
    id: lint-name
    attributes:
      label: Lint Name
      description: Please provide the lint name.
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: >
        What category should this lint go into? If you're unsure you can select
        multiple categories.
      multiple: true
      options:
        - api
        - comment
        - complexity
        - debug
        - exceptions
        - general
        - naming
        - oop
        - structure
        - unnecessary
  - type: textarea
    id: example
    attributes:
      label: Example
      description: >
        Include a short example showing when the lint should trigger together
        with the improved code.
      value: |
        ```java
        <code>
        ```

        Could be written as:

        ```java
        <code>
        ```
    validations:
      required: true
