p-ui-input-separation = Input and Business Logic not sufficiently separated
p-output-separation = Output and Business Logic not sufficiently separated
p-avoid-inner-classes = Avoid inner classes
p-use-string-formatted = Use String#formatted()
p-optional-tri-state = Avoid Optional\<Boolean\>
p-avoid-labels = Avoid labels
p-simplify-arrays-fill = Unnecessary start and length arguments
p-duplicate-catch-block = Duplicate catch block
p-duplicate-if-block = Duplicate if block
p-redundant-assignment = Unused value
p-avoid-shadowing = Avoid shadowing parent fields
p-collections-n-copies = Simplify with Collections.nCopies()
p-do-not-use-system-exit = Don't use System.exit()
p-scanner-must-be-closed = Scanner not closed
p-equals-hashcode-comparable-contract = Equals/hashCode/Comparable contract violated
p-unchecked-type-cast = Unchecked type cast
p-too-many-exceptions = Too many exceptions defined
p-implement-comparable = Implement Comparable instead of using Comparator
p-magic-string = Magic string
p-constant-name-contains-value = Meaningless name (contains value)
p-deprecated-collection-used = Collection is deprecated
p-collection-is-empty-reimplemented = Use isEmpty()
