package de.firemage.autograder.core.check.complexity;

import de.firemage.autograder.core.ProblemType;
import de.firemage.autograder.core.pmd.PMDCheck;
import net.sourceforge.pmd.lang.java.rule.codestyle.UnnecessaryConstructorRule;

public class RedundantConstructorCheck extends PMDCheck {
    private static final String DESCRIPTION =
        "The default constructor is implicitly generated by the compiler when there is no explicit constructor";

    public RedundantConstructorCheck() {
        super(DESCRIPTION, DESCRIPTION, new UnnecessaryConstructorRule(), ProblemType.REDUNDANT_DEFAULT_CONSTRUCTOR);
    }
}
