name: Maven Build

on:
  push:
    branches:
      - 'main' # Build the latest develop-SNAPSHOT
    paths-ignore:
      - 'Readme.md'
      - 'LICENSE.md'
      - 'checks.md'
      - 'sample_config.yaml'
      - 'test_submissions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  build:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: joshlong/java-version-export-github-action@v28
        id: jve
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ steps.jve.outputs.java_major_version }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml && mvn -B test --file pom.xml
        
      - uses: actions/upload-artifact@v4
        with:
          name: autograder-cmd
          path: |
            autograder-cmd/target/autograder-cmd.jar
            autograder-full/target/autograder-full.jar
          if-no-files-found: error

      # Release only when pushing to a tag
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: 'Minor Release (mostly for the automatic download of the jar file)'
          files: |
              autograder-cmd/target/autograder-cmd.jar
              autograder-full/target/autograder-full.jar
